// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { mergeAdditionalBodyParameters } from "../../../../core/requestBody.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import type * as CodeRustcApi from "../../../index.js";

export declare namespace PetsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class PetsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<PetsClient.Options>;

    constructor(options: PetsClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * @param {CodeRustcApi.ListPetsRequest} request
     * @param {PetsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link errors.CodeRustcApiError}
     * @throws {@link errors.CodeRustcApiTimeoutError}
     *
     * @example
     *     await client.pets.listPets()
     */
    public listPets(
        request: CodeRustcApi.ListPetsRequest = {},
        requestOptions?: PetsClient.RequestOptions,
    ): core.HttpResponsePromise<CodeRustcApi.Pet[]> {
        return core.HttpResponsePromise.fromPromise(this.__listPets(request, requestOptions));
    }

    private async __listPets(
        request: CodeRustcApi.ListPetsRequest = {},
        requestOptions?: PetsClient.RequestOptions,
    ): Promise<core.WithRawResponse<CodeRustcApi.Pet[]>> {
        const { limit } = request;
        const _queryParams: Record<string, unknown> = {
            limit,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.CodeRustcApiEnvironment.Default,
                "pets",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as CodeRustcApi.Pet[], rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.CodeRustcApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/pets");
    }

    /**
     * @param {CodeRustcApi.NewPet} request
     * @param {PetsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link errors.CodeRustcApiError}
     * @throws {@link errors.CodeRustcApiTimeoutError}
     *
     * @example
     *     await client.pets.createPet({
     *         name: "Rex",
     *         tag: "dog"
     *     })
     */
    public createPet(
        request: CodeRustcApi.NewPet,
        requestOptions?: PetsClient.RequestOptions,
    ): core.HttpResponsePromise<CodeRustcApi.Pet> {
        return core.HttpResponsePromise.fromPromise(this.__createPet(request, requestOptions));
    }

    private async __createPet(
        request: CodeRustcApi.NewPet,
        requestOptions?: PetsClient.RequestOptions,
    ): Promise<core.WithRawResponse<CodeRustcApi.Pet>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.CodeRustcApiEnvironment.Default,
                "pets",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as CodeRustcApi.Pet, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.CodeRustcApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/pets");
    }

    /**
     * @param {CodeRustcApi.GetPetRequest} request
     * @param {PetsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link errors.CodeRustcApiError}
     * @throws {@link errors.CodeRustcApiTimeoutError}
     *
     * @example
     *     await client.pets.getPet({
     *         petId: 1
     *     })
     */
    public getPet(
        request: CodeRustcApi.GetPetRequest,
        requestOptions?: PetsClient.RequestOptions,
    ): core.HttpResponsePromise<CodeRustcApi.Pet> {
        return core.HttpResponsePromise.fromPromise(this.__getPet(request, requestOptions));
    }

    private async __getPet(
        request: CodeRustcApi.GetPetRequest,
        requestOptions?: PetsClient.RequestOptions,
    ): Promise<core.WithRawResponse<CodeRustcApi.Pet>> {
        const { petId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.CodeRustcApiEnvironment.Default,
                `pets/${core.url.encodePathParam(petId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as CodeRustcApi.Pet, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.CodeRustcApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/pets/{petId}");
    }
}
