// This file was auto-generated by Fern from our API Definition.

import { CodeRustcApiClient } from '../../src/Client';
import { mockServerPool } from '../mock-server/MockServerPool';

describe('PetsClient', () => {
  test('listPets', async () => {
    const server = mockServerPool.createServer();
    const client = new CodeRustcApiClient({
      maxRetries: 0,
      token: 'test',
      environment: server.baseUrl,
    });

    const rawResponseBody = [{ name: 'Rex', tag: 'dog', id: 1 }];

    server
      .mockEndpoint()
      .get('/pets')
      .respondWith()
      .statusCode(200)
      .jsonBody(rawResponseBody)
      .build();

    const response = await client.pets.listPets();
    expect(response).toEqual(rawResponseBody);
  });

  test('createPet', async () => {
    const server = mockServerPool.createServer();
    const client = new CodeRustcApiClient({
      maxRetries: 0,
      token: 'test',
      environment: server.baseUrl,
    });
    const rawRequestBody = { name: 'Rex', tag: 'dog' };
    const rawResponseBody = { name: 'Rex', tag: 'dog', id: 1 };

    server
      .mockEndpoint()
      .post('/pets')
      .jsonBody(rawRequestBody)
      .respondWith()
      .statusCode(200)
      .jsonBody(rawResponseBody)
      .build();

    const response = await client.pets.createPet({
      name: 'Rex',
      tag: 'dog',
    });
    expect(response).toEqual(rawResponseBody);
  });

  test('getPet', async () => {
    const server = mockServerPool.createServer();
    const client = new CodeRustcApiClient({
      maxRetries: 0,
      token: 'test',
      environment: server.baseUrl,
    });

    const rawResponseBody = { name: 'Rex', tag: 'dog', id: 1 };

    server
      .mockEndpoint()
      .get('/pets/1')
      .respondWith()
      .statusCode(200)
      .jsonBody(rawResponseBody)
      .build();

    const response = await client.pets.getPet({
      petId: 1,
    });
    expect(response).toEqual(rawResponseBody);
  });
});
