// This file was auto-generated by Fern from our API Definition.

export const CodeRustcApiEnvironment = {
  Default: 'https://petstore.example.com/v1',
} as const;

export type CodeRustcApiEnvironment = typeof CodeRustcApiEnvironment.Default;
